title:             Astri's Blog
email:             situkangsayur@gmail.com
description:       A Blog to share my experiences
author:            Astri Lestari
baseurl:           "/"
url:               "http://lestariastri.github.io"

# Social Profiles
twitter_username:  infoHendri
github_username:   lestariastri
facebook_username: itsastrilestariworld

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
