title:             Astri's Blog
email:             lestariastri6@gmail.com
description:       Ikatlah ilmu dengan menuliskannya - Ali bin Abi Thalib
author:            Astri Lestari
baseurl:           "/"
url:               "https://lestariastri.github.io"

# Social Profiles
twitter_username:  infoHendri
github_username:   lestariastri
facebook_username: itsastrilestariworld
#diqus
comments: true
# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
